<a href="https://colab.research.google.com/github/jiang-h-y/gait-condition-classification/blob/main/gait_condition_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
!pip install tsfresh
!pip install ucimlrepo

Requirement already satisfied: tsfresh in /usr/local/lib/python3.12/dist-packages (0.21.1)
Requirement already satisfied: requests>=2.9.1 in /usr/local/lib/python3.12/dist-packages (from tsfresh) (2.32.4)
Requirement already satisfied: numpy>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from tsfresh) (2.0.2)
Requirement already satisfied: pandas>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from tsfresh) (2.2.2)
Requirement already satisfied: statsmodels>=0.13 in /usr/local/lib/python3.12/dist-packages (from tsfresh) (0.14.6)
Requirement already satisfied: patsy>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from tsfresh) (1.0.2)
Requirement already satisfied: pywavelets in /usr/local/lib/python3.12/dist-packages (from tsfresh) (1.9.0)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from tsfresh) (1.6.1)
Requirement already satisfied: tqdm>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from tsfresh) (4.67.3)
Requirement already satisfied: stumpy>=1.7.2 in /usr/local/lib/python3.12/dist-packages (from tsfresh) (1.13.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from tsfresh) (3.1.2)
Requirement already satisfied: scipy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from tsfresh) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.0->tsfresh) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.0->tsfresh) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.0->tsfresh) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.1->tsfresh) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.1->tsfresh) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.1->tsfresh) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.1->tsfresh) (2026.2.25)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->tsfresh) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->tsfresh) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13->tsfresh) (26.0)
Requirement already satisfied: numba>=0.57.1 in /usr/local/lib/python3.12/dist-packages (from stumpy>=1.7.2->tsfresh) (0.60.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.57.1->stumpy>=1.7.2->tsfresh) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.0->tsfresh) (1.17.0)
Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [37]:
from tsfresh import extract_features, select_features

In [33]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
multivariate_gait_data = fetch_ucirepo(id=760)

# store data as df
df = multivariate_gait_data.data.features

In [34]:
df

        subject  condition  replication  leg  joint  time      angle
0             1          1            1    1      1     0   4.682881
1             1          1            1    1      1     1   5.073127
2             1          1            1    1      1     2   5.229774
3             1          1            1    1      1     3   5.083273
4             1          1            1    1      1     4   4.652399
...         ...        ...          ...  ...    ...   ...        ...
181795       10          3           10    2      3    96  29.778412
181796       10          3           10    2      3    97  29.247559
181797       10          3           10    2      3    98  28.796951
181798       10          3           10    2      3    99  28.432936
181799       10          3           10    2      3   100  28.136438

[181800 rows x 7 columns]

In [35]:
ts_df = df.copy()
ts_df["subject_rep"] = df["subject"].astype("str") + "_" + df["replication"].astype("str")
ts_df["leg_joint"] = df["leg"].astype("str") + "_" + df["joint"].astype("str")

In [36]:
ts_df

,subject,condition,replication,leg,joint,time,angle,subject_rep,leg_joint
0,1,1,1,1,1,0,4.682881,1_1,1_1
1,1,1,1,1,1,1,5.073127,1_1,1_1
2,1,1,1,1,1,2,5.229774,1_1,1_1
3,1,1,1,1,1,3,5.083273,1_1,1_1
4,1,1,1,1,1,4,4.652399,1_1,1_1
...,...,...,...,...,...,...,...,...,...
181795,10,3,10,2,3,96,29.778412,10_10,2_3
181796,10,3,10,2,3,97,29.247559,10_10,2_3
181797,10,3,10,2,3,98,28.796951,10_10,2_3
181798,10,3,10,2,3,99,28.432936,10_10,2_3
181799,10,3,10,2,3,100,28.136438,10_10,2_3

In [30]:
extract_features(ts_df, column_id="subject_rep", column_kind="leg_joint", column_sort="time", column_value="angle")

WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 600/600 [02:31<00:00,  3.96it/s]

,1_1__variance_larger_than_standard_deviation,1_1__has_duplicate_max,1_1__has_duplicate_min,1_1__has_duplicate,1_1__sum_values,1_1__abs_energy,1_1__mean_abs_change,1_1__mean_change,1_1__mean_second_derivative_central,1_1__median,...,2_3__fourier_entropy__bins_5,2_3__fourier_entropy__bins_10,2_3__fourier_entropy__bins_100,2_3__permutation_entropy__dimension_3__tau_1,2_3__permutation_entropy__dimension_4__tau_1,2_3__permutation_entropy__dimension_5__tau_1,2_3__permutation_entropy__dimension_6__tau_1,2_3__permutation_entropy__dimension_7__tau_1,2_3__query_similarity_count__query_None__threshold_0.0,2_3__mean_n_absolute_max__number_of_maxima_7
10_1,1.0,0.0,0.0,0.0,1677.770883,20615.932914,1.520057,0.013596,0.002051,6.957270,...,0.136002,0.136002,0.181214,1.775488,3.093643,4.403550,5.139348,5.414395,NaN,33.250343
10_10,1.0,0.0,0.0,0.0,1495.668007,20715.101350,2.559502,0.006438,0.007804,5.876729,...,0.136002,0.136002,0.181214,1.779667,3.080588,4.370591,5.088993,5.365821,NaN,34.401530
10_2,1.0,0.0,0.0,0.0,1516.378398,20281.999840,1.834901,0.008412,0.001047,6.207650,...,0.136002,0.136002,0.181214,1.783544,3.097285,4.380606,5.146859,5.417783,NaN,33.845823
10_3,1.0,0.0,0.0,0.0,1371.494837,17868.729183,1.788758,0.007967,-0.004575,5.520188,...,0.090729,0.136002,0.181214,1.787592,3.095326,4.435667,5.168108,5.376240,NaN,35.215461
10_4,1.0,0.0,0.0,0.0,1422.722177,20203.217009,1.927681,0.009803,0.004503,5.798984,...,0.136002,0.136002,0.181214,1.756136,3.058627,4.344576,5.077025,5.391832,NaN,33.936753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9_5,1.0,0.0,0.0,0.0,1996.617337,25470.915264,1.534074,0.009941,0.002768,7.237388,...,0.090729,0.136002,0.181214,1.789237,3.108281,4.445111,5.183204,5.420629,NaN,29.627980
9_6,1.0,0.0,0.0,0.0,2003.786681,23708.523371,1.668520,0.009736,-0.000002,7.190517,...,0.090729,0.136002,0.181214,1.779954,3.118078,4.451655,5.106687,5.392683,NaN,31.254964
9_7,1.0,0.0,0.0,0.0,1813.797356,21431.813554,1.591360,0.010082,0.001000,6.624015,...,0.090729,0.136002,0.181214,1.773357,3.083649,4.390908,5.089609,5.341865,NaN,31.790751
9_8,1.0,0.0,0.0,0.0,1691.666997,21968.593371,1.697390,0.011917,0.000044,6.246241,...,0.090729,0.136002,0.136002,1.763940,3.069204,4.346639,5.059244,5.354724,NaN,29.971891
9_9,1.0,0.0,0.0,0.0,1729.314203,21542.047505,2.006468,0.016105,0.000620,6.241207,...,0.090729,0.136002,0.181214,1.780216,3.097133,4.394558,5.110626,5.403780,NaN,29.905417